# Generated by Django 3.1.3 on 2022-05-17 13:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crediti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('cf', models.CharField(max_length=255)),
                ('coordinateCatastali', models.CharField(max_length=255)),
                ('isovalore', models.CharField(max_length=10)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3003)),
                ('volumetria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('causale', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, blank=True)),
                ('time_stamp', models.DateTimeField()),
                ('data', models.TextField(blank=True, max_length=255)),
                ('hash', models.CharField(blank=True, max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(blank=True, default=0, max_length=255)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recred.crediti')),
            ],
        ),
    ]
