# Generated by Django 3.2.11 on 2022-11-25 10:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import recred.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anagrafica',
            fields=[
                ('cf', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[recred.models.validate_cf])),
                ('consente_trattamento_dati', models.BooleanField()),
                ('cognome', models.CharField(max_length=255, verbose_name='cognome/denominazione')),
                ('nome', models.CharField(max_length=255, verbose_name='nome/suffisso')),
                ('indirizzo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Anagrafica',
                'verbose_name_plural': 'Anagrafica',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, blank=True)),
                ('time_stamp', models.DateTimeField()),
                ('data', models.TextField(blank=True, max_length=255)),
                ('hash', models.CharField(blank=True, max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(blank=True, default=0, max_length=255)),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Crediti',
            },
        ),
        migrations.CreateModel(
            name='zona_isovalore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3003)),
                ('codice_zona', models.CharField(max_length=10)),
                ('denominazione', models.CharField(max_length=110)),
                ('areeurb_valoreconvenzionale', models.IntegerField()),
                ('areeurb_valorearea', models.IntegerField()),
                ('areenonurb_valorearea', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='utilizzo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('coordinateCatastali', models.CharField(max_length=255)),
                ('isovalore_destinazione', models.CharField(max_length=10)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3003)),
                ('ammontare_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('causale', models.CharField(max_length=255)),
                ('destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizzi_destinazione', to='recred.block')),
                ('origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizzi_origine', to='recred.block')),
                ('residuo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizzi_residuo', to='recred.block')),
            ],
            options={
                'verbose_name': 'Utilizzo',
                'verbose_name_plural': 'Utilizzi',
            },
        ),
        migrations.CreateModel(
            name='trasferimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('repertorio', models.CharField(max_length=255)),
                ('ammontare_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_destinazione', to='recred.block')),
                ('origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_origine', to='recred.block')),
                ('residuo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_residuo', to='recred.block')),
                ('titolare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recred.anagrafica')),
            ],
            options={
                'verbose_name': 'Trasferimento',
                'verbose_name_plural': 'Trasferimenti',
            },
        ),
        migrations.CreateModel(
            name='formazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('coordinateCatastali', models.CharField(max_length=255)),
                ('isovalore', models.CharField(choices=[('B1', 'B1 - CENTRO STORICO ENTRO RIVIERE-VIA XX SETTEMBRE'), ('B2', 'B2 - CENTRO STORICO FUORI RIVIERE-VIA XX SETTEMBRE'), ('C1', 'C1 - PORTELLO'), ('C2', 'C2 - STAZIONE,SCROVEGNI,C.SO DEL POPOLO,FIERA, CITTADELLA'), ('C3', 'C3 - BORGOMAGNO, PRIMA ARCELLA, PESCAROTTO'), ('C4', 'C4 - ZONA DIREZIONALE PADOVAUNO'), ('C5', 'C5 - MADONNA PELLEGRINA, S.RITA, NAZARETH,SANT`OSVALDO'), ('C6a', 'C6a - PALESTRO, SACRA FAMIGLIA, SAN GIUSEPPE'), ('C6b', 'C6b - PORTA TRENTO'), ('D1', 'D1 - CHIESANUOVA,BRUSEGANA'), ('D2', 'D2 - PALTANA, VOLTABRUSEGANA, MANDRIA'), ('D3', 'D3 - BASSANELLO, GUIZZA, VOLTABAROZZO'), ('D4', 'D4 - PONTE DI BRENTA, SAN LAZZARO'), ('D5a', "D5a - SANT'IGNAZIO, MONTA'"), ('D5b', 'D5b - SACRO CUORE'), ('D6', 'D6 - TORRE, PONTEVIGODARZERE, SACRO CUORE'), ('D7', 'D7 - ARCELLA NORD, MORTISE'), ('D8a', 'D8a - FORCELLINI EST'), ('D8b', 'D8b - SAN GREGORIO'), ('D8c', 'D8c - TERRANEGRA'), ('E1', 'E1 - CAMIN'), ('E2', 'E2 - ZONA INDUSTRIALE,ZIP'), ('E3', 'E3 - SALBORO'), ('R1', 'R1 - RURALE NORD COMPRENDE QUARTIERE PONTEROTTO'), ('R2', 'R2 - RURALE OVEST'), ('R3', 'R3 - RURALE SUD')], max_length=60)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3003)),
                ('ammontare_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('CE', 'Crediti edilizi'), ('CER', 'Crediti edilizi da rinaturalizzazione')], max_length=3)),
                ('descrizione', models.CharField(max_length=255)),
                ('titolare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recred.anagrafica')),
            ],
            options={
                'verbose_name': 'Formazione',
                'verbose_name_plural': 'Formazioni',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recred.formazione'),
        ),
    ]
