# Generated by Django 3.1.3 on 2022-05-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formazione',
            name='isovalore',
        ),
        migrations.AddField(
            model_name='formazione',
            name='zona_isovalore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recred.isovalore'),
        ),
        migrations.AlterModelTable(
            name='isovalore',
            table='zone_isovalore',
        ),
    ]
