# Generated by Django 3.1.3 on 2022-05-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transazioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causale', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('cf', models.CharField(max_length=255)),
                ('repertorio', models.CharField(max_length=255)),
                ('volumetria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destinazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_destinazione', to='recred.block')),
                ('origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_origine', to='recred.block')),
            ],
        ),
    ]
