# Generated by Django 3.1.3 on 2022-05-18 09:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0002_transazioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transazioni',
            name='causale',
            field=models.CharField(default='transazione', max_length=20),
        ),
        migrations.AlterField(
            model_name='transazioni',
            name='destinazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_destinazione', to='recred.block'),
        ),
        migrations.AlterField(
            model_name='transazioni',
            name='volumetria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='utilizzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('cf', models.CharField(max_length=255)),
                ('coordinateCatastali', models.CharField(max_length=255)),
                ('isovalore', models.CharField(max_length=10)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3003)),
                ('volumetria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('causale', models.CharField(max_length=255)),
                ('destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizzi_destinazione', to='recred.block')),
                ('origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizzi_origine', to='recred.block')),
            ],
        ),
    ]
