# Generated by Django 3.1.3 on 2022-05-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0003_auto_20220518_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='transazioni',
            name='residuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_residuo', to='recred.block'),
        ),
        migrations.AddField(
            model_name='utilizzi',
            name='residuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizzi_residuo', to='recred.block'),
        ),
    ]
