# Generated by Django 3.1.3 on 2022-05-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0004_auto_20220518_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transazioni',
            name='causale',
        ),
        migrations.RemoveField(
            model_name='utilizzi',
            name='cf',
        ),
        migrations.RemoveField(
            model_name='utilizzi',
            name='nome',
        ),
    ]
