# Generated by Django 3.1.3 on 2022-05-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0005_auto_20220518_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crediti',
            old_name='causale',
            new_name='descrizione',
        ),
    ]
