# Generated by Django 3.1.3 on 2022-05-23 11:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0006_auto_20220518_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='isovalore',
            fields=[
                ('fid', models.IntegerField(db_column='ogc_fid', primary_key=True, serialize=False)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(blank=True, db_column='the_geom', srid=3003)),
                ('codice_zona', models.TextField(blank=True, db_column='ZONA_ISO', null=True)),
                ('denominazione', models.TextField(blank=True, db_column='DENOM', null=True)),
            ],
            options={
                'verbose_name': 'Zone di isovalore',
                'verbose_name_plural': 'Zona di isovalore',
                'db_table': 'visio_zone_isovalore',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Blocchi', 'verbose_name_plural': 'Blocchi'},
        ),
        migrations.AlterModelOptions(
            name='crediti',
            options={'verbose_name': 'Credito edilizio', 'verbose_name_plural': 'Crediti edilizi'},
        ),
        migrations.AlterModelOptions(
            name='transazioni',
            options={'verbose_name': 'Transazione', 'verbose_name_plural': 'Transazioni'},
        ),
        migrations.AlterModelOptions(
            name='utilizzi',
            options={'verbose_name': 'Utilizzo', 'verbose_name_plural': 'Utilizzi'},
        ),
    ]
