# Generated by Django 3.1.3 on 2022-05-24 10:35

from django.db import migrations, models
import recred.models


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0008_auto_20220524_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='crediti',
            name='cer',
            field=models.BooleanField(default=False, verbose_name='Crediti da rinaturalizzazione'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crediti',
            name='cf',
            field=models.CharField(max_length=255, validators=[recred.models.validate_cf]),
        ),
        migrations.AlterField(
            model_name='crediti',
            name='isovalore',
            field=models.CharField(choices=[('B1', 'B1 - CENTRO STORICO ENTRO RIVIERE-VIA XX SETTEMBRE'), ('B2', 'B2 - CENTRO STORICO FUORI RIVIERE-VIA XX SETTEMBRE'), ('C1', 'C1 - PORTELLO'), ('C2', 'C2 - STAZIONE,SCROVEGNI,C.SO DEL POPOLO,FIERA, CITTADELLA'), ('C3', 'C3 - BORGOMAGNO, PRIMA ARCELLA, PESCAROTTO'), ('C4', 'C4 - ZONA DIREZIONALE PADOVAUNO'), ('C5', 'C5 - MADONNA PELLEGRINA, S.RITA, NAZARETH,SANT`OSVALDO'), ('C6a', 'C6a - PALESTRO, SACRA FAMIGLIA, SAN GIUSEPPE'), ('C6b', 'C6b - PORTA TRENTO'), ('D1', 'D1 - CHIESANUOVA,BRUSEGANA'), ('D2', 'D2 - PALTANA, VOLTABRUSEGANA, MANDRIA'), ('D3', 'D3 - BASSANELLO, GUIZZA, VOLTABAROZZO'), ('D4', 'D4 - PONTE DI BRENTA, SAN LAZZARO'), ('D5a', "D5a - SANT'IGNAZIO, MONTA'"), ('D5b', 'D5b - SACRO CUORE'), ('D6', 'D6 - TORRE, PONTEVIGODARZERE, SACRO CUORE'), ('D7', 'D7 - ARCELLA NORD, MORTISE'), ('D8a', 'D8a - FORCELLINI EST'), ('D8b', 'D8b - SAN GREGORIO'), ('D8c', 'D8c - TERRANEGRA'), ('E1', 'E1 - CAMIN'), ('E2', 'E2 - ZONA INDUSTRIALE,ZIP'), ('E3', 'E3 - SALBORO'), ('R1', 'R1 - RURALE NORD COMPRENDE QUARTIERE PONTEROTTO'), ('R2', 'R2 - RURALE OVEST'), ('R3', 'R3 - RURALE SUD')], max_length=60),
        ),
        migrations.AlterField(
            model_name='transazioni',
            name='cf',
            field=models.CharField(max_length=255, validators=[recred.models.validate_cf]),
        ),
    ]
