# Generated by Django 3.1.3 on 2022-05-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recred', '0009_auto_20220524_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crediti',
            name='cer',
        ),
        migrations.AddField(
            model_name='crediti',
            name='tipo',
            field=models.CharField(choices=[('CE', 'Crediti edilizi'), ('CER', 'Crediti edilizi da rinaturalizzazione')], default='CE', max_length=3),
            preserve_default=False,
        ),
    ]
